/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __RS_TENSORFLOW_TYPE_DEFINITIONS_H__
#define __RS_TENSORFLOW_TYPE_DEFINITIONS_H__


#endif /* __RS_TENSORFLOW_TYPE_DEFINITIONS_H__ */
